# permissions for end users to edit escalations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: escalation-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: grafana-oncall-operator
    app.kubernetes.io/part-of: grafana-oncall-operator
    app.kubernetes.io/managed-by: kustomize
  name: escalation-editor-role
rules:
- apiGroups:
  - oncall.ahcogn.com
  resources:
  - escalations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - oncall.ahcogn.com
  resources:
  - escalations/status
  verbs:
  - get
