# permissions for end users to view integrations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: integration-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: grafana-oncall-operator
    app.kubernetes.io/part-of: grafana-oncall-operator
    app.kubernetes.io/managed-by: kustomize
  name: integration-viewer-role
rules:
- apiGroups:
  - oncall.ahcogn
  resources:
  - integrations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - oncall.ahcogn
  resources:
  - integrations/status
  verbs:
  - get
