---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - oncall.ahcogn
  resources:
  - integrations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - oncall.ahcogn
  resources:
  - integrations/finalizers
  verbs:
  - update
- apiGroups:
  - oncall.ahcogn
  resources:
  - integrations/status
  verbs:
  - get
  - patch
  - update
